### ISSUE TITLE
Lots of Lines in Big Sur

### ISSUE THREAD

**Issue by runblip** [TheSlowGrowth/VCOTuner#27]
Just moved to a new machine running Big Sur, having this issue:
![Screen Shot 2021-02-09 at 8 05 58 PM](https://user-images.githubusercontent.com/78831740/107449853-4ff56e00-6b12-11eb-9bcf-ada7fef647bb.png)

**Comment by TheSlowGrowth** [comment]
Oh wow, that looks bad!
I'l see what I can do to fix this, thanks for reporting!

**Comment by runblip** [comment]
Thanks for looking into it! This is a great tool you have built

**Comment by kstammits** [comment]
I've got this fixed by recompiling with JUCE v6 on Big Sur.  No substantial changes in the app code, but the frameworks have moved a lot in macOS11. I posted the binary at the Modwiggler thread, but I'm not sure if it's good for other platforms.

https://github.com/kstammits/VCOTuner/releases/tag/v0.3.0

**Comment by TheSlowGrowth** [comment]
Ah thank you so much. My own attempts haven't been successful but time has also been sparse lately. Since you have it as a fork already, would you mind to make a Pull Request? I'll make sure it still works on windows as well.

**Comment by kstammits** [comment]
I have created the PR. Unfortunately changing JUCE v4 to v6 involved touching 1500 files, so this is a messy update.
